---
- name: install packages
  apt: name={{ item }}
  become: true
  with_items:
      - vim
      # /usr/share/doc/build-essential/essential-packages-list
      - build-essential
      - supervisor
      - python-pip
      - python-dev
      - python3-dev
      - "{% if ansible_distribution_release in ['trusty', 'jessie'] %}python-virtualenv{% else %}virtualenv{% endif %}"
      - libffi-dev
      - libssl-dev
      - unzip
      - p7zip-full
      - git
      - mercurial
      - subversion
      - ufw
      - mosh
      - openssh-server
      - curl
      - aria2
      - tree
      # mailtuils
      - cmake
      - gdebi
      - debconf-utils
      - htop
      # apt-file # apt-file update
      # fail2ban
      - screen
      - telnet
      #- bind9utils
      - dnsutils
      - ntpdate
      - "{% if ansible_distribution_release == 'trusty' %}openjdk-7-jdk{% else %}openjdk-8-jdk{% endif %}"
      - mysql-client-5.6
      - libmysqlclient-dev
      - libzmq3-dev
      - jq # and jo
- name: add wildcard supervisord include
  ini_file: dest=/etc/supervisor/supervisord.conf
            section=include
            option=files
            value="/etc/supervisor/conf.d/*.conf {{ ansible_user_dir }}/srv/*/supervisord-*.conf"
            backup=yes
  become: true
- name: Allow SSH, HTTP
  ufw: rule=allow port={{ item }}
  become: true
  with_items:
      - 22
      - 80
      - 443
  when: sel is defined
- name: Allow mosh in UFW
  ufw: rule=allow port=60000:61000 proto=udp
  become: true
  when: sel is defined
- name: Set firewall default policy
  ufw: state=enabled policy=deny
  become: true
  when: sel is defined
- name: check timezone
  lineinfile: dest=/etc/timezone line="Asia/Shanghai" regexp="^.*$" backup=yes
  become: true
  register: timezone
- name: change timezone
  shell: dpkg-reconfigure --frontend noninteractive tzdata
  become: true
  when: timezone.changed
