---
- name: install packages
  apt: name={{ item }}
  become: true
  with_items:
    - shellcheck
    - tasksel
    - astyle
    - graphviz
    - dstat
    - gnuplot
    - sqlite3
    - libfreetype6-dev
    - bison
    - redis-server
    - mysql-server
- name: upgrade mysql-server to 5.6
  # http://dev.mysql.com/get/mysql-apt-config_0.3.5-1ubuntu14.04_all.deb
  command: apt-get install --yes mysql-server-5.6 mysql-server-core-5.6 mysql-client-5.6 mysql-client-core-5.6
  become: true
  args:
      creates: /etc/logcheck/ignore.d.server/mysql-server-5_6
  when: ansible_distribution_release == 'trusty'
- name: install rustup
  shell: curl https://sh.rustup.rs -sSf --connect-timeout 3 | sh -s - -y
  args:
      creates: "{{ ansible_env.HOME }}/.cargo/env"
  #TODO ~/.cargo/bin to $PATH
- name: install rust nightly
  command: bash -c '. {{ ansible_env.HOME }}/.cargo/env && rustup default nightly'
  # bash rustup.sh --channel=nightly
- name: install nvm
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
  args:
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
- name: install nodejs
  shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install v6.0.0
- name: install gvm
  shell: curl --connect-timeout 3 -sSL https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer | bash
  args:
      creates: "{{ ansible_env.HOME }}/.gvm/scripts/gvm"
- name: install go1.4 on trusty
  shell: bash -c '. {{ ansible_env.HOME }}/.gvm/scripts/gvm && gvm install go1.4'
  when: ansible_distribution_release == 'trusty'
- name: install go1.4
  # https://github.com/golang/go/issues/13114#issuecomment-186922245
  shell: bash -c '. {{ ansible_env.HOME }}/.gvm/scripts/gvm && CGO_ENABLED=0 gvm install go1.4'
  when: ansible_distribution_release != 'trusty'
- name: install go1.6.2
  shell: bash -c '. {{ ansible_env.HOME }}/.gvm/scripts/gvm && gvm use go1.4 && gvm install go1.6.2'
- name: import rvm key
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
- name: install rvm with rails
  # --rails
  shell: curl -sSL https://get.rvm.io | bash -s stable
  args:
      creates: "{{ ansible_env.HOME }}/.rvm/scripts/rvm"
